version: '3.7'

services:
  wemoney-api:
    build: ./Backend/WeMoney
    container_name: wemoney-api
    restart: unless-stopped
    ports:
      - '8080:80'
      - '3030:443'
    volumes:
      - keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mongodb
      - nginx

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - ALLOWED_IP=127.0.0.1

volumes:
  keys:
  mongo-data: